# Generated by Django 5.2.14 on 2026-06-02 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del consultorio o sala. Único por clínica.",
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ubicación física (piso, ala, edificio, etc.).",
                        max_length=200,
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Color en formato hexadecimal (#RRGGBB) para el calendario.",
                        max_length=7,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = consultorio inactivo (soft). No borra el registro.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "personal_consultorios",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "cedula_profesional",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cédula profesional emitida por la SEP.",
                        max_length=30,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Especialidad médica. Texto libre en v1; catálogo en v2.",
                        max_length=100,
                    ),
                ),
                (
                    "default_appointment_duration",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Duración default de cita para este médico, en minutos.",
                    ),
                ),
                (
                    "bio_short",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Semblanza corta del médico (máx 255 caracteres).",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = médico inactivo (soft). No borra el registro.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.OneToOneField(
                        help_text="Membresía del médico en esta clínica. Role debe ser 'doctor'.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_profile",
                        to="tenancy.tenantmembership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "personal_doctors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        help_text="Día de la semana (0=Lunes, 6=Domingo).",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Hora de inicio en hora LOCAL del tenant (no UTC). Ver docstring del modelo."
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="Hora de fin en hora LOCAL del tenant (no UTC). Debe ser > start_time."
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Fecha desde la que aplica este horario (inclusive). Null = sin límite.",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Fecha hasta la que aplica este horario (inclusive). Null = sin límite.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = horario desactivado (soft). Se ignora en la agenda.",
                    ),
                ),
                (
                    "consultorio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Consultorio asignado a este bloque (opcional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="personal.consultorio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Médico al que pertenece este bloque de horario.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="personal.doctor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "personal_doctor_schedules",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="consultorio",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="consultorio_tenant_name_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorschedule",
            index=models.Index(
                fields=["tenant", "doctor", "day_of_week"], name="schedule_doctor_day_idx"
            ),
        ),
    ]
