# Generated by Django 5.2.14 on 2026-06-02 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_enable_rls"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="membership",
            field=models.ForeignKey(
                help_text="Membresía del médico en esta clínica. Role debe ser 'doctor'.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doctor_profile",
                to="tenancy.tenantmembership",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("membership",),
                name="doctor_membership_active_uniq",
            ),
        ),
    ]
