# Generated by Django 5.2.14 on 2026-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0003_alter_doctor_membership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="consultorios",
            field=models.ManyToManyField(
                blank=True,
                help_text="Consultorios donde ESTE médico puede atender. Vacío = sin restricción (puede usar cualquiera). Todos deben pertenecer al mismo tenant que el doctor.",
                related_name="doctores",
                to="personal.consultorio",
            ),
        ),
    ]
