# Generated by Django 5.2.14 on 2026-06-17 20:29

import apps.personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0004_doctor_consultorios"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="cedulas_adicionales",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cédulas profesionales adicionales separadas por coma (especialidades, subespecialidades).",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Fotografía del médico para encabezados de receta (JPG/PNG/WEBP, máx 5 MB).",
                null=True,
                upload_to=apps.personal.models._doctor_foto_path,
                validators=[apps.personal.models._validate_doctor_image],
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="sello",
            field=models.ImageField(
                blank=True,
                help_text="Sello o firma escaneada del médico (JPG/PNG/WEBP, máx 5 MB).",
                null=True,
                upload_to=apps.personal.models._doctor_sello_path,
                validators=[apps.personal.models._validate_doctor_image],
            ),
        ),
    ]
