# Generated by Django 5.2.15 on 2026-07-02 15:43

import apps.personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Fotografía del médico para encabezados de receta (JPG/PNG/WEBP, máx 5 MB).",
                max_length=255,
                null=True,
                upload_to=apps.personal.models._doctor_foto_path,
                validators=[apps.personal.models._validate_doctor_image],
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="sello",
            field=models.ImageField(
                blank=True,
                help_text="Sello o firma escaneada del médico (JPG/PNG/WEBP, máx 5 MB).",
                max_length=255,
                null=True,
                upload_to=apps.personal.models._doctor_sello_path,
                validators=[apps.personal.models._validate_doctor_image],
            ),
        ),
    ]
