# Generated by Django 5.2.15 on 2026-07-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0016_sucursal_membershipsucursal_and_more"),
        ("personal", "0007_rls_with_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultorio",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal a la que pertenece este consultorio (multi-sede — Fase 1). Null = sin asignar (compatibilidad retro; el backfill de la Fase 1 asigna todos los consultorios existentes a la Sucursal Principal).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultorios",
                to="clinica.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="sucursales",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sucursales donde ESTE médico puede atender (multi-sede — Fase 1). Vacío = sin restricción (compatibilidad retro: clínicas de una sola sede no necesitan asignar nada). Todas deben pertenecer al mismo tenant que el doctor.",
                related_name="doctores",
                to="clinica.sucursal",
            ),
        ),
    ]
