# Generated by Django 5.2.15 on 2026-07-14 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0018_rls_membership_sucursales"),
        ("personal", "0009_backfill_sucursal_principal"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorschedule",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal (sede) a la que pertenece este horario laboral (multi-sede — Fase 2). Se resuelve del consultorio asignado, de la sede activa del request, o de la predeterminada del tenant si no se indica explícitamente.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_schedules",
                to="clinica.sucursal",
            ),
        ),
    ]
