# Generated by Django 5.2.14 on 2026-06-09 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Título breve de la nota (opcional).",
                        max_length=120,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Cuerpo de la nota (opcional). Al menos title o body deben tener contenido.",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("role", "Rol específico"),
                            ("all", "Todos"),
                        ],
                        db_index=True,
                        default="personal",
                        help_text="Audiencia de la nota: personal / role / all.",
                        max_length=10,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Rol destinatario cuando scope=role. Vacío en scope=personal o scope=all. Valores válidos: owner, admin, doctor, nurse, reception, finance, readonly.",
                        max_length=20,
                    ),
                ),
                (
                    "is_task",
                    models.BooleanField(
                        default=False,
                        help_text="Si True, la nota es una tarea (muestra checkbox de done/pendiente).",
                    ),
                ),
                (
                    "done",
                    models.BooleanField(
                        default=False,
                        help_text="Estado de la tarea. Solo relevante cuando is_task=True.",
                    ),
                ),
                (
                    "remind_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha/hora UTC del recordatorio. Null = sin recordatorio.",
                        null=True,
                    ),
                ),
                (
                    "pinned",
                    models.BooleanField(default=False, help_text="Fijada al tope del listado."),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Usuario que creó la nota.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "notas_notes",
                "ordering": ["-pinned", "-created_at"],
            },
        ),
    ]
