# Generated by Django 5.2.14 on 2026-06-02 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0, help_text="Último número de expediente asignado en esta clínica."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pacientes_patient_sequences",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Nombre(s) del paciente.", max_length=120),
                ),
                (
                    "paternal_surname",
                    models.CharField(help_text="Apellido paterno.", max_length=120),
                ),
                (
                    "maternal_surname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Apellido materno (opcional).",
                        max_length=120,
                    ),
                ),
                ("date_of_birth", models.DateField(help_text="Fecha de nacimiento.")),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("X", "Otro")],
                        help_text="Sexo del paciente según NOM-024 (M/F/X).",
                        max_length=1,
                    ),
                ),
                (
                    "curp",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CURP del paciente. Único por clínica cuando se provee.",
                        max_length=18,
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Teléfono de contacto (WhatsApp).", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Correo electrónico (opcional).",
                        max_length=254,
                    ),
                ),
                (
                    "record_number",
                    models.CharField(
                        help_text="Número de expediente generado automáticamente. No editar manualmente.",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Notas internas del expediente."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = expediente desactivado (soft). No borra el registro.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pacientes_patients",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "paternal_surname", "maternal_surname"],
                        name="patient_apellidos_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "record_number"), name="patient_record_number_uniq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("curp", ""), _negated=True),
                        fields=("tenant", "curp"),
                        name="patient_curp_uniq",
                    ),
                ],
            },
        ),
    ]
