# Generated by Django 5.2.14 on 2026-06-02 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_enable_rls"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patientsequence",
            constraint=models.UniqueConstraint(
                fields=("tenant",), name="patient_sequence_tenant_uniq"
            ),
        ),
    ]
