# Generated by Django 5.2.14 on 2026-06-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0003_patientsequence_patient_sequence_tenant_uniq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="record_number",
            field=models.CharField(
                help_text="Número de expediente generado automáticamente. No editar manualmente.",
                max_length=30,
            ),
        ),
    ]
