# Generated by Django 5.2.14 on 2026-06-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0004_alter_patient_record_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_provisional",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True = expediente creado al vuelo desde la agenda con datos mínimos. Falta completar la información personal (fecha nac., sexo, etc.).",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Fecha de nacimiento. Puede ser null en expedientes provisionales.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Teléfono de contacto (WhatsApp). Vacío en provisionales.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino"), ("X", "Otro")],
                default="",
                help_text="Sexo del paciente según NOM-024 (M/F/X). Vacío en provisionales.",
                max_length=1,
            ),
        ),
    ]
