# Generated by Django 5.2.14 on 2026-06-09 16:34

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0005_patient_is_provisional_alter_patient_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Foto del paciente (opcional).",
                null=True,
                upload_to=apps.core.files.patient_avatar_path,
            ),
        ),
    ]
