# Generated by Django 5.2.14 on 2026-06-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0006_patient_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_favorite",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Marcado como favorito (visible para toda la clínica).",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_vip",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Paciente VIP (visible para toda la clínica).",
            ),
        ),
    ]
