# Generated by Django 5.2.14 on 2026-06-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0006_patient_nom004_fields"),
        ("pacientes", "0007_patient_is_favorite_is_vip"),
    ]

    operations = []
