# Generated by Django 5.2.15 on 2026-06-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0008_doctorcredential_validation_note_and_more"),
        ("pacientes", "0008_merge_20260616_1224"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Etiquetas asignadas al paciente desde el catálogo de la clínica. Con ellas el médico organiza y filtra a sus pacientes. Todas deben pertenecer al mismo tenant que el paciente.",
                related_name="patients",
                to="clinica.patientcategory",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Categoría libre (legacy v1). Se conserva por compatibilidad; la clasificación nueva usa `categories` (etiquetas del catálogo).",
                max_length=60,
            ),
        ),
    ]
