# Generated by Django 5.2.15 on 2026-06-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0010_migrar_favorito_vip_a_etiquetas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="is_favorite",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="is_vip",
        ),
    ]
