# Generated by Django 5.2.15 on 2026-06-25 19:49
#
# Índices de trigramas (pg_trgm) para la búsqueda libre de pacientes.
#
# patient_list (apps/pacientes/selectors.py) filtra con icontains sobre
# first_name | paternal_surname | maternal_surname | phone | record_number
# unidos por OR. Para que Postgres pueda resolver ese OR por índice (BitmapOr)
# en vez de un seq scan O(n) por cada tecleo del buscador, CADA campo del OR
# necesita su propio índice GIN de trigramas. Por eso son 5 índices.
#
# TrigramExtension crea `pg_trgm` (CREATE EXTENSION IF NOT EXISTS) y DEBE ir
# antes de los AddIndex que usan el opclass gin_trgm_ops.

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0011_remove_patient_is_favorite_remove_patient_is_vip"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="patient",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["first_name"], name="patient_first_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["paternal_surname"],
                name="patient_paternal_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["maternal_surname"],
                name="patient_maternal_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["phone"], name="patient_phone_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["record_number"], name="patient_record_num_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
