# Generated by Django 5.2.15 on 2026-07-02 15:43

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0012_patient_patient_first_name_trgm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Foto del paciente (opcional).",
                max_length=255,
                null=True,
                upload_to=apps.core.files.patient_avatar_path,
            ),
        ),
    ]
