# Generated by Django 5.2.15 on 2026-07-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0005_rls_treatment_packages"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceconcept",
            name="clinical_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Descripción CLÍNICA del tratamiento (distinta de `description`, que es comercial). Se usa como texto sugerido en la sección 'Descripción de los tratamientos' del Plan Integral de Longevidad (apps.expediente) cuando este concepto se incluye en un esquema de calendarización.",
            ),
        ),
    ]
