# Generated by Django 5.2.15 on 2026-07-14 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0018_rls_membership_sucursales"),
        ("finanzas", "0006_serviceconcept_clinical_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal (sede) donde se GENERÓ el cargo (multi-sede — Fase 3). Null = dato legado sin backfillar, o tenant sin sucursales. NO se usa para filtrar el estado de cuenta del paciente (compartido entre sedes); sí para acotar reportes/caja por sede.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="clinica.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal (sede) donde se GENERÓ el pago (multi-sede — Fase 3). Null = dato legado sin backfillar, o tenant sin sucursales. NO se usa para filtrar el estado de cuenta del paciente (compartido entre sedes); sí para acotar reportes/caja por sede.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="clinica.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal (sede) donde se GENERÓ la cotización (multi-sede — Fase 3). Null = dato legado sin backfillar, o tenant sin sucursales. NO se usa para filtrar el estado de cuenta del paciente (compartido entre sedes); sí para acotar reportes/caja por sede.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="clinica.sucursal",
            ),
        ),
    ]
