# Generated by Django 5.2.15 on 2026-07-15 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0018_rls_membership_sucursales"),
        ("finanzas", "0008_backfill_charge_payment_quote_sucursal"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfdidocument",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal (sede) donde se GENERÓ el CFDI (multi-sede — Fase 3, clúster D). Heredada de `payment.sucursal` al timbrar. Null = dato legado sin backfillar, o tenant sin sucursales. Se usa para acotar listado/detalle/timbrado/cancelación por sede (integridad fiscal: un admin de una sede no debe timbrar ni cancelar CFDI de otra).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="clinica.sucursal",
            ),
        ),
    ]
