# Generated by Django 5.2.15 on 2026-07-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0018_rls_membership_sucursales"),
        ("finanzas", "0010_backfill_cfdidocument_sucursal"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceconcept",
            name="sucursales",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sucursales donde este servicio está disponible (multi-sede — decisión del dueño, 2026-07-16). El PRECIO es el mismo en todas las sedes (base_price); esto solo controla disponibilidad. CONVENCIÓN: vacío = disponible en TODAS las sedes del tenant.",
                related_name="+",
                to="clinica.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="treatmentpackage",
            name="sucursales",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sucursales donde este paquete está disponible (multi-sede — decisión del dueño, 2026-07-16). El PRECIO es el mismo en todas las sedes (suma de base_price de sus líneas); esto solo controla disponibilidad. CONVENCIÓN: vacío = disponible en TODAS las sedes del tenant.",
                related_name="+",
                to="clinica.sucursal",
            ),
        ),
    ]
