# Generated by Django 5.2.15 on 2026-07-21 18:53

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0012_rls_finanzas_m2m_through_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="global_discount_type",
            field=models.CharField(
                choices=[("amount", "Monto"), ("percent", "Porcentaje")],
                default="amount",
                help_text="Tipo del descuento GENERAL de la cotización (además del descuento por renglón). 'amount' = monto fijo en $, 'percent' = porcentaje sobre la suma de los renglones ya descontados. Default 'amount' — compatibilidad retro.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="global_discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valor CAPTURADO del descuento general: monto en $ o porcentaje (0-100) según `global_discount_type`. Default 0 — compatibilidad retro (cotizaciones existentes no cambian de total).",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Descuento EFECTIVO en $ ya aplicado a la línea (calculado por el servicio desde `discount`/`discount_type`, recortado a la base si la excede). Snapshot para no recalcular en cada lectura/reporte/PDF.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="quoteitem",
            name="discount_type",
            field=models.CharField(
                choices=[("amount", "Monto"), ("percent", "Porcentaje")],
                default="amount",
                help_text="Tipo de descuento del renglón: 'amount' = monto fijo en $, 'percent' = porcentaje (0-100) sobre `quantity * unit_price`. Default 'amount' — compatibilidad retro.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Valor CAPTURADO del descuento: monto en $ o porcentaje (0-100), según `discount_type`. NO es directamente el descuento en pesos cuando discount_type='percent' — usar `discount_amount` para el monto efectivo.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="quoteitem",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Importe de la línea = (cantidad * precio) - discount_amount (calculado). Nunca negativo.",
                max_digits=12,
            ),
        ),
    ]
