# Generated by Django 5.2.14 on 2026-06-02 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='NULL = activo. Rellenar para borrado lógico.', null=True)),
                ('name', models.CharField(help_text='Nombre comercial de la clínica.', max_length=200)),
                ('slug', models.SlugField(help_text='Identificador URL-safe único. Ej: clinica-san-jose', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('trial', 'En prueba'), ('active', 'Activa'), ('suspended', 'Suspendida')], db_index=True, default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='Fecha de fin del periodo de prueba. Null = sin límite.', null=True)),
                ('timezone', models.CharField(default='America/Mexico_City', help_text='Zona horaria del tenant para localizar fechas. Usar nombres IANA.', max_length=64)),
            ],
            options={
                'db_table': 'tenancy_tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='NULL = activo. Rellenar para borrado lógico.', null=True)),
                ('role', models.CharField(choices=[('owner', 'Dueño'), ('admin', 'Administrador'), ('doctor', 'Médico'), ('nurse', 'Enfermería'), ('reception', 'Recepción'), ('finance', 'Finanzas'), ('readonly', 'Solo lectura')], help_text='Rol del usuario dentro de la clínica.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False = acceso suspendido (sin borrar la membresía).')),
                ('tenant', models.ForeignKey(help_text='Clínica a la que pertenece la membresía.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.tenant')),
                ('user', models.ForeignKey(help_text='Usuario miembro de la clínica.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenancy_memberships',
                'indexes': [models.Index(fields=['tenant', 'role'], name='membership_tenant_role_idx')],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
