# Generated by Django 5.2.14 on 2026-06-02 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_enable_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tenantmembership",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(fields=["user", "is_active"], name="membership_user_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="tenantmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "tenant"), name="membership_user_tenant_uniq"
            ),
        ),
    ]
