# Generated by Django 5.2.15 on 2026-07-02 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador estable del plan. Ej: 'basico', 'pro', 'premium'.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Nombre comercial del plan.", max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Descripción comercial breve del plan."
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2, help_text="Precio mensual en MXN.", max_digits=10
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Plan destacado/recomendado en la vitrina de planes.",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text="Lista de strings con las características incluidas en el plan.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = plan retirado del catálogo (no asignable a nuevas suscripciones).",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de despliegue en la vitrina de planes (ascendente).",
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_plans",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="tenant",
            name="trial_expired_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Marca de idempotencia: cuándo se registró el aviso (evento de auditoría TRIAL_EXPIRED) de que el trial ya venció. Null = no avisado todavía. Se resetea si el trial se extiende (nuevo trial_ends_at posterior a esta marca) para poder volver a avisar.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Mensual"), ("annual", "Anual")],
                        help_text="Ciclo de facturación contratado.",
                        max_length=10,
                    ),
                ),
                (
                    "current_period_end",
                    models.DateField(
                        help_text="Fecha en que vence el periodo de facturación vigente."
                    ),
                ),
                (
                    "period_expired_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Marca de idempotencia: cuándo se registró el aviso (evento de auditoría SUBSCRIPTION_EXPIRED) de que el periodo ya venció. Null = no avisado todavía. Se resetea al renovar/cambiar el plan con una current_period_end futura.",
                        null=True,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Plan asignado. PROTECT: no se puede borrar un plan con suscripciones activas.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="tenancy.plan",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        help_text="Clínica suscrita.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_subscriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
