# Generated by Django 5.2.15 on 2026-07-24 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0005_seed_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="max_consultorios",
            field=models.PositiveIntegerField(
                blank=True, help_text="Máximo de consultorios. NULL = ilimitado.", null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_sucursales",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Máximo de sucursales. NULL = ilimitado. El valor 1 activa el 'modo sede única': se oculta toda la UI de sucursales.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_usuarios",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Máximo de miembros activos de la clínica. NULL = ilimitado.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="modules",
            field=models.JSONField(
                default=list,
                help_text="Slugs de apps.core.modules.Module incluidos en el plan. Esto SÍ controla el acceso (el backend es la autoridad).",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="features",
            field=models.JSONField(
                default=list,
                help_text="Lista de strings de MARKETING que se muestran en la vitrina. NO controla acceso: para eso está `modules`.",
            ),
        ),
        migrations.CreateModel(
            name="TenantEntitlements",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "modules_on",
                    models.JSONField(
                        default=list,
                        help_text="Módulos concedidos ADEMÁS de los del plan (add-ons, cortesías).",
                    ),
                ),
                (
                    "modules_off",
                    models.JSONField(
                        default=list, help_text="Módulos revocados aunque el plan los traiga."
                    ),
                ),
                (
                    "max_sucursales",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override del límite del plan. NULL = usar el del plan.",
                        null=True,
                    ),
                ),
                (
                    "max_consultorios",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override del límite del plan. NULL = usar el del plan.",
                        null=True,
                    ),
                ),
                (
                    "max_usuarios",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override del límite del plan. NULL = usar el del plan.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Por qué se concedió este trato especial. Obligatorio en la práctica: sin el motivo, nadie sabe si el ajuste sigue vigente al renovar.",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        help_text="Clínica a la que aplican estos ajustes.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "tenant entitlements",
                "db_table": "tenancy_entitlements",
            },
        ),
    ]
