# Generated by Django 5.2.15 on 2026-07-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0007_entitlements_legacy_full"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Roles que el plan ofrece al dar de alta miembros. Lista VACÍA = sin restricción extra (todos los que los módulos permitan). Un rol solo aparece si además su módulo está activo (ej. 'finance' necesita cobranza). Ej. Básico: ['owner','doctor','nurse','reception'].",
            ),
        ),
    ]
