# Generated by Django 5.2.14 on 2026-06-17 20:29

import apps.clinica.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0005_initial"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorUniversity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        help_text="Logo de la universidad/institución. JPG/PNG/WEBP, máx 5 MB.",
                        upload_to=apps.clinica.models.doctor_university_logo_path,
                        validators=[apps.clinica.models.validate_clinic_image],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre de la institución (opcional si el logo es suficiente).",
                        max_length=200,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Médico al que pertenece esta institución educativa.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="universities",
                        to="personal.doctor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "clinica_doctor_universities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo de la clínica (JPG/PNG/WEBP, máx 5 MB).",
                        null=True,
                        upload_to=apps.clinica.models.clinic_logo_path,
                        validators=[apps.clinica.models.validate_clinic_image],
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Dirección principal de la clínica.",
                        max_length=300,
                    ),
                ),
                (
                    "address_2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Complemento de dirección (colonia, referencias, etc.).",
                        max_length=300,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", help_text="Teléfono fijo.", max_length=30
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Teléfono móvil / WhatsApp.",
                        max_length=30,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Email de contacto de la clínica.",
                        max_length=254,
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, default="", help_text="URL del sitio web.", max_length=200
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL o handle de Facebook.",
                        max_length=200,
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL o handle de Instagram.",
                        max_length=200,
                    ),
                ),
                (
                    "youtube",
                    models.CharField(
                        blank=True, default="", help_text="URL o handle de YouTube.", max_length=200
                    ),
                ),
                (
                    "letterhead_full",
                    models.ImageField(
                        blank=True,
                        help_text="Membrete de hoja completa (carta). JPG/PNG/WEBP, máx 5 MB.",
                        null=True,
                        upload_to=apps.clinica.models.clinic_letterhead_full_path,
                        validators=[apps.clinica.models.validate_clinic_image],
                    ),
                ),
                (
                    "letterhead_half",
                    models.ImageField(
                        blank=True,
                        help_text="Membrete de media hoja. JPG/PNG/WEBP, máx 5 MB.",
                        null=True,
                        upload_to=apps.clinica.models.clinic_letterhead_half_path,
                        validators=[apps.clinica.models.validate_clinic_image],
                    ),
                ),
                (
                    "letterhead_full_spaces",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Líneas en blanco a respetar después del membrete de hoja completa.",
                    ),
                ),
                (
                    "letterhead_half_spaces",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Líneas en blanco a respetar después del membrete de media hoja.",
                    ),
                ),
                (
                    "recipe_use_responsible_doctor",
                    models.BooleanField(
                        default=False,
                        help_text="Si True, todas las recetas se imprimen con el nombre del médico responsable (no el tratante). Útil cuando hay un responsable sanitario.",
                    ),
                ),
                (
                    "recipe_whatsapp_contacts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lista de contactos de WhatsApp para envío de recetas. Estructura: [{"nombre": "...", "numero": "..."}, ...].',
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "clinica_settings",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant",),
                        name="clinic_settings_tenant_active_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClinicTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("recipe", "Receta"),
                            ("document", "Documento"),
                            ("consent", "Consentimiento informado"),
                        ],
                        db_index=True,
                        help_text="Tipo de plantilla: receta, documento o consentimiento.",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre identificador de la plantilla.", max_length=200
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Cuerpo de la plantilla. Texto libre; puede incluir variables {placeholder}."
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Grupo o categoría temática (p. ej. 'PECAJEN', 'GINECOLOGÍA').",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = plantilla desactivada (soft). No se borra físicamente.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "clinica_templates",
                "ordering": ["kind", "name"],
                "indexes": [
                    models.Index(fields=["tenant", "kind"], name="clinic_tmpl_tenant_kind_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PatientCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la categoría (p. ej. 'VIP', 'Asegurado IMSS').",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = categoría desactivada (soft-delete).",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "clinica_patient_categories",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant", "name"),
                        name="clinic_category_tenant_name_active_uniq",
                    )
                ],
            },
        ),
    ]
