# Generated by Django 5.2.14 on 2026-06-18 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0002_enable_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicsettings",
            name="letterhead_full_spaces",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Líneas en blanco a respetar después del membrete de hoja completa. Máximo 200 (anti-DoS: evita generar PDFs con alturas descomunales).",
                validators=[django.core.validators.MaxValueValidator(200)],
            ),
        ),
        migrations.AlterField(
            model_name="clinicsettings",
            name="letterhead_half_spaces",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Líneas en blanco a respetar después del membrete de media hoja. Máximo 200 (anti-DoS: evita generar PDFs con alturas descomunales).",
                validators=[django.core.validators.MaxValueValidator(200)],
            ),
        ),
    ]
