# Generated by Django 5.2.14 on 2026-06-18 20:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0003_add_max_value_validator_letterhead_spaces"),
        ("personal", "0005_initial"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="commercial_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre comercial de la clínica para el membrete de la receta. Puede diferir de Tenant.name (p. ej. 'Clínica Camsa' vs 'CAMSA S.A. de C.V.'). COFEPRIS F2.",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="DoctorCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Nombre del título o grado académico, sin abreviaturas. Ej: 'Médico Cirujano y Partero', 'Maestría en Cirugía Estética'.",
                        max_length=200,
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        help_text="Institución que expide el título. Ej: 'Universidad Nacional Autónoma de México'. COFEPRIS obligatorio.",
                        max_length=200,
                    ),
                ),
                (
                    "credential_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número de cédula profesional o de especialidad. Ej: '12345678'. Puede estar en blanco si es posgrado sin cédula.",
                        max_length=60,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("profesional", "Cédula profesional"),
                            ("especialidad", "Cédula de especialidad"),
                            ("posgrado", "Posgrado (maestría / doctorado)"),
                        ],
                        db_index=True,
                        help_text="Tipo de credencial: profesional, especialidad o posgrado.",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Orden de aparición en el membrete (0 = primero). Permite controlar qué cédula aparece en qué posición.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = credencial dada de baja (baja lógica, sin borrado físico).",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Médico al que pertenece esta credencial.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="personal.doctor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "clinica_doctor_credentials",
                "ordering": ["doctor", "order", "id"],
                "indexes": [
                    models.Index(fields=["tenant", "doctor"], name="cred_tenant_doctor_idx"),
                    models.Index(
                        fields=["tenant", "doctor", "kind"], name="cred_tenant_doctor_kind_idx"
                    ),
                ],
            },
        ),
    ]
