# Generated by Django 5.2.15 on 2026-06-22 18:57

import apps.clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0005_rls_doctor_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorcredential",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo opcional de la institución que expide la credencial. JPG/PNG/WEBP, máx 5 MB.",
                null=True,
                upload_to=apps.clinica.models.doctor_credential_logo_path,
                validators=[apps.clinica.models.validate_clinic_image],
            ),
        ),
    ]
