# Generated by Django 5.2.15 on 2026-06-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0006_add_logo_to_doctor_credential"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicsettings",
            name="recipe_use_responsible_doctor",
        ),
        migrations.RemoveField(
            model_name="clinicsettings",
            name="recipe_whatsapp_contacts",
        ),
    ]
