# Generated by Django 5.2.15 on 2026-06-22 21:36

from django.db import migrations, models


def _grandfather_existing(apps, schema_editor):
    """Las credenciales que ya existían quedan VALIDADAS (estaban en uso).

    El flujo de validación es nuevo: para no hacer desaparecer credenciales que
    ya se usaban en recetas, las preexistentes se marcan 'validada'. Las nuevas
    entrarán como 'pendiente' (default del campo).
    """
    DoctorCredential = apps.get_model("clinica", "DoctorCredential")
    DoctorCredential.objects.update(validation_status="validada")


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0007_remove_recipe_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorcredential",
            name="validation_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Motivo del rechazo o nota de la validación administrativa (opcional).",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="doctorcredential",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente de validación"),
                    ("validada", "Validada"),
                    ("rechazada", "Rechazada"),
                ],
                db_index=True,
                default="pendiente",
                help_text="Estado de validación: el médico la captura como 'pendiente'; un administrador la marca 'validada' o 'rechazada'. Solo las validadas aparecen en la receta.",
                max_length=12,
            ),
        ),
        migrations.RunPython(_grandfather_existing, _noop),
    ]
