# Generated by Django 5.2.15 on 2026-06-23 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0008_doctorcredential_validation_note_and_more"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patientcategory",
            name="kind",
            field=models.CharField(
                choices=[
                    ("custom", "Personalizada"),
                    ("favorite", "Favorito (sistema)"),
                    ("vip", "VIP (sistema)"),
                ],
                db_index=True,
                default="custom",
                help_text="custom = creada por el médico; favorite/vip = del sistema (no se borran).",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="patientcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), models.Q(("kind", "custom"), _negated=True)
                ),
                fields=("tenant", "kind"),
                name="clinic_category_one_system_per_kind",
            ),
        ),
    ]
