# Generated by Django 5.2.15 on 2026-06-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0009_patientcategory_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="doctors_see_costs",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Si está activo, los médicos ven el estado de cuenta del paciente dentro del expediente/libro. Por defecto desactivado (D-2).",
            ),
        ),
    ]
