# Generated by Django 5.2.15 on 2026-06-26 18:33

import apps.clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0010_doctors_see_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="brand_color",
            field=models.CharField(
                blank=True,
                default="#9A7B1E",
                help_text="Color de marca de la clínica en formato #RRGGBB (p. ej. '#3A7BD5'). Se usa como color de acento en encabezados y fondos de PDF. Valor por defecto: dorado Maily #9A7B1E.",
                max_length=7,
                validators=[apps.clinica.models.validate_hex_color],
            ),
        ),
    ]
