# Generated by Django 5.2.15 on 2026-07-02 15:43

import apps.clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0011_add_brand_color_to_clinic_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicsettings",
            name="letterhead_full",
            field=models.ImageField(
                blank=True,
                help_text="Membrete de hoja completa (carta). JPG/PNG/WEBP, máx 5 MB.",
                max_length=255,
                null=True,
                upload_to=apps.clinica.models.clinic_letterhead_full_path,
                validators=[apps.clinica.models.validate_clinic_image],
            ),
        ),
        migrations.AlterField(
            model_name="clinicsettings",
            name="letterhead_half",
            field=models.ImageField(
                blank=True,
                help_text="Membrete de media hoja. JPG/PNG/WEBP, máx 5 MB.",
                max_length=255,
                null=True,
                upload_to=apps.clinica.models.clinic_letterhead_half_path,
                validators=[apps.clinica.models.validate_clinic_image],
            ),
        ),
        migrations.AlterField(
            model_name="clinicsettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo de la clínica (JPG/PNG/WEBP, máx 5 MB).",
                max_length=255,
                null=True,
                upload_to=apps.clinica.models.clinic_logo_path,
                validators=[apps.clinica.models.validate_clinic_image],
            ),
        ),
        migrations.AlterField(
            model_name="doctorcredential",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo opcional de la institución que expide la credencial. JPG/PNG/WEBP, máx 5 MB.",
                max_length=255,
                null=True,
                upload_to=apps.clinica.models.doctor_credential_logo_path,
                validators=[apps.clinica.models.validate_clinic_image],
            ),
        ),
    ]
