# Generated by Django 5.2.15 on 2026-07-13 21:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.clinica.models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0015_rls_clinic_team_members"),
        ("tenancy", "0005_seed_plans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la sucursal (p. ej. 'Sucursal Centro', 'Sucursal Norte').",
                        max_length=160,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Dirección física de la sucursal (opcional).",
                        max_length=255,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Teléfono de contacto de la sucursal (opcional).",
                        max_length=40,
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Color en formato #RRGGBB para distinguir la sede en la agenda (uso futuro, Fase 2). Opcional.",
                        max_length=7,
                        validators=[apps.clinica.models.validate_hex_color],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = sucursal desactivada (soft). No borra el registro.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True = sucursal predeterminada del tenant (única por clínica). Se asigna vía sucursal_set_default, nunca por PATCH directo.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "clinica_sucursales",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MembershipSucursal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        help_text="Membresía (usuario + rol) del tenant asignada a la sucursal.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursales_asignadas",
                        to="tenancy.tenantmembership",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        help_text="Sucursal en la que opera la membresía.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membresias",
                        to="clinica.sucursal",
                    ),
                ),
            ],
            options={
                "db_table": "tenancy_membership_sucursales",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="sucursal",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="sucursal_tenant_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="sucursal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("tenant",),
                name="sucursal_tenant_one_default_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipsucursal",
            constraint=models.UniqueConstraint(
                fields=("membership", "sucursal"), name="membership_sucursal_uniq"
            ),
        ),
    ]
