# Generated by Django 5.2.14 on 2026-06-15 15:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("meeting", "Reunión"),
                            ("team_note", "Nota de equipo"),
                            ("role_note", "Nota dirigida a un rol"),
                            ("broadcast", "Aviso a toda la clínica"),
                        ],
                        db_index=True,
                        help_text="Tipo de evento que originó la notificación.",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Texto principal de la notificación (ya armado para mostrar).",
                        max_length=160,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, default="", help_text="Texto secundario opcional."
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("appointment", "Cita"),
                            ("agenda_block", "Evento de agenda"),
                            ("note", "Nota"),
                        ],
                        default="",
                        help_text="Tipo de objeto destino para el enlace. Vacío = sin destino.",
                        max_length=20,
                    ),
                ),
                (
                    "target_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID del objeto destino. Null si target_type está vacío.",
                        null=True,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha/hora UTC en que se marcó como leída. Null = no leída.",
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que disparó el evento. Null si fue el sistema o fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Usuario que recibe la notificación.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "notificaciones_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient", "read_at"], name="notif_recip_read_idx"),
                    models.Index(
                        fields=["recipient", "-created_at"], name="notif_recip_created_idx"
                    ),
                ],
            },
        ),
    ]
