# Generated by Django 5.2.15 on 2026-06-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0003_add_nursing_instruction_and_patient_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("meeting", "Reunión"),
                    ("team_note", "Nota de equipo"),
                    ("role_note", "Nota dirigida a un rol"),
                    ("broadcast", "Aviso a toda la clínica"),
                    ("nursing_instruction", "Indicación de enfermería"),
                    ("credential_review", "Credencial por validar"),
                    ("credential_result", "Resultado de validación de credencial"),
                ],
                db_index=True,
                help_text="Tipo de evento que originó la notificación.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("appointment", "Cita"),
                    ("agenda_block", "Evento de agenda"),
                    ("note", "Nota"),
                    ("patient", "Paciente"),
                    ("credential", "Credencial de médico"),
                ],
                default="",
                help_text="Tipo de objeto destino para el enlace. Vacío = sin destino.",
                max_length=20,
            ),
        ),
    ]
