# Generated by Django 5.2.15 on 2026-06-29 19:20

import apps.pdfs.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=40)),
                ("cache_key", models.CharField(blank=True, default="", max_length=200)),
                ("params", models.JSONField(default=dict)),
                ("filename", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("done", "Listo"),
                            ("failed", "Falló"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="PDF generado; None hasta que la tarea termina.",
                        null=True,
                        upload_to=apps.pdfs.models.pdf_job_path,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pdfs_pdf_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "kind", "status"], name="pdf_job_kind_status_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("cache_key", ""), _negated=True),
                        fields=("tenant", "kind", "cache_key"),
                        name="pdf_job_cache_uniq",
                    )
                ],
            },
        ),
    ]
