# Generated by Django 5.2.15 on 2026-07-02 15:43

import apps.pdfs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdfs", "0002_rls_pdf_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfjob",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="PDF generado; None hasta que la tarea termina.",
                max_length=255,
                null=True,
                upload_to=apps.pdfs.models.pdf_job_path,
            ),
        ),
    ]
