# Generated by Django 5.2.14 on 2026-06-18 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalMedication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(
                        db_index=True,
                        help_text="Denominación Común Internacional (DCI) o nombre genérico del principio activo. Ej: 'Paracetamol', 'Amoxicilina', 'Metformina'. NUNCA incluir indicaciones ni dosis recomendadas (DR-7).",
                        max_length=200,
                    ),
                ),
                (
                    "commercial_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Nombre comercial de referencia (opcional). Ej: 'Panadol', 'Tempra'. No es el único nombre posible; es solo referencia.",
                        max_length=200,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("tableta", "Tableta"),
                            ("capsula", "Cápsula"),
                            ("jarabe", "Jarabe"),
                            ("suspension", "Suspensión"),
                            ("solucion", "Solución"),
                            ("solucion_inyectable", "Solución inyectable"),
                            ("crema", "Crema"),
                            ("unguento", "Ungüento"),
                            ("gel", "Gel"),
                            ("gotas", "Gotas"),
                            ("ovulo", "Óvulo"),
                            ("supositorio", "Supositorio"),
                            ("parche", "Parche"),
                            ("aerosol", "Aerosol"),
                            ("polvo", "Polvo"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        help_text="Forma farmacéutica. Ej: tableta, jarabe, solución inyectable.",
                        max_length=20,
                    ),
                ),
                (
                    "concentration",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Concentración estándar del principio activo. Ej: '500 mg', '250 mg/5 mL', '10 mg/mL'. Solo concentraciones de uso común bien conocidas; dejar en blanco si hay duda (DR-7).",
                        max_length=100,
                    ),
                ),
                (
                    "presentation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Presentación comercial estándar. Ej: 'Caja con 20 tabletas', 'Frasco 120 mL'. Solo presentaciones estándar bien conocidas; dejar en blanco si hay duda (DR-7).",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="True = medicamento vigente en el catálogo. False = retirado o descontinuado (no aparece en autocompletado).",
                    ),
                ),
            ],
            options={
                "db_table": "recetas_global_medications",
                "ordering": ["generic_name", "form", "concentration"],
                "indexes": [
                    models.Index(fields=["generic_name", "form"], name="global_med_name_form_idx"),
                    models.Index(fields=["commercial_name"], name="global_med_commercial_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(
                        db_index=True,
                        help_text="Denominación genérica o nombre propio del médico para este medicamento. NUNCA incluir indicaciones ni dosis recomendadas (DR-7).",
                        max_length=200,
                    ),
                ),
                (
                    "commercial_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre comercial de referencia (opcional).",
                        max_length=200,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("tableta", "Tableta"),
                            ("capsula", "Cápsula"),
                            ("jarabe", "Jarabe"),
                            ("suspension", "Suspensión"),
                            ("solucion", "Solución"),
                            ("solucion_inyectable", "Solución inyectable"),
                            ("crema", "Crema"),
                            ("unguento", "Ungüento"),
                            ("gel", "Gel"),
                            ("gotas", "Gotas"),
                            ("ovulo", "Óvulo"),
                            ("supositorio", "Supositorio"),
                            ("parche", "Parche"),
                            ("aerosol", "Aerosol"),
                            ("polvo", "Polvo"),
                            ("otro", "Otro"),
                        ],
                        db_index=True,
                        help_text="Forma farmacéutica.",
                        max_length=20,
                    ),
                ),
                (
                    "concentration",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Concentración del principio activo (opcional). Ej: '500 mg'.",
                        max_length=100,
                    ),
                ),
                (
                    "presentation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Presentación (opcional). Ej: 'Caja con 20 tabletas'.",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="True = medicamento vigente (aparece en autocompletado). False = dado de baja (baja clínica, sin borrado físico — DR-5).",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "recetas_medications",
                "ordering": ["generic_name", "form", "concentration"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "generic_name"], name="medication_tenant_name_idx"
                    ),
                    models.Index(
                        fields=["tenant", "is_active"], name="medication_tenant_active_idx"
                    ),
                ],
            },
        ),
    ]
