# Generated by Django 5.2.14 on 2026-06-18 15:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0010_appointment_reschedule_count"),
        ("expediente", "0013_rls_evolution_images"),
        ("pacientes", "0008_merge_20260616_1224"),
        ("personal", "0005_initial"),
        ("recetas", "0002_rls_medication"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "folio",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Número de folio consecutivo por tenant. Generado automáticamente con SELECT FOR UPDATE. Único por tenant (UniqueConstraint).",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora de emisión de la receta. Por defecto = ahora.",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Recomendaciones generales del médico al paciente (opcional).",
                        max_length=5000,
                    ),
                ),
                (
                    "vitals_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot de la última toma de signos vitales del paciente al crear la receta. Estructura: {weight_kg, height_m, imc, heart_rate, resp_rate, systolic, diastolic, temperature_c, oxygen_saturation, glucose, measured_at}. Null si el paciente no tiene tomas registradas al momento de crear. DR-7: congela los signos — cambios futuros no alteran la receta.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activa"), ("cancelled", "Anulada")],
                        db_index=True,
                        default="active",
                        help_text="Estado de la receta. Solo puede ir de active → cancelled.",
                        max_length=10,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de anulación. Null si la receta está activa.",
                        null=True,
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Motivo de la anulación. Requerido al cancelar; en blanco si activa.",
                        max_length=500,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cita médica asociada (opcional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="agenda.appointment",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que anuló la receta. Null si la receta está activa.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Médico que emite la receta (inferido del perfil activo del usuario).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="personal.doctor",
                    ),
                ),
                (
                    "evolution_note",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nota de evolución asociada (opcional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="expediente.evolutionnote",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Paciente al que se emite la receta.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="pacientes.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "recetas_prescriptions",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Orden del renglón en la receta (1-based). Permite presentación ordenada.",
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(
                        help_text="Nombre del medicamento (snapshot al crear). Requerido. Es la fuente de verdad inmutable del documento. DR-7: el catálogo puede cambiar; la receta no.",
                        max_length=200,
                    ),
                ),
                (
                    "medication_presentation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Presentación del medicamento (snapshot). Ej: 'Caja con 20 tabletas'.",
                        max_length=200,
                    ),
                ),
                (
                    "medication_form",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Forma farmacéutica del medicamento (snapshot). Ej: 'tableta'.",
                        max_length=20,
                    ),
                ),
                (
                    "medication_concentration",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Concentración del medicamento (snapshot). Ej: '500 mg'.",
                        max_length=100,
                    ),
                ),
                (
                    "indication",
                    models.TextField(
                        help_text="Indicación del médico: dosis, frecuencia y duración. Ej: '1 tableta cada 8 horas por 7 días con alimentos'. Requerido."
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cantidad a dispensar (opcional). Ej: '20 tabletas', '1 frasco'.",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "global_medication",
                    models.ForeignKey(
                        blank=True,
                        help_text="FK al catálogo global (opcional, solo trazabilidad). El snapshot de texto es la fuente de verdad.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescription_items",
                        to="recetas.globalmedication",
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        blank=True,
                        help_text="FK al medicamento custom del tenant (opcional, solo trazabilidad). El snapshot de texto es la fuente de verdad.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescription_items",
                        to="recetas.medication",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        help_text="Receta a la que pertenece este renglón.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="recetas.prescription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "recetas_prescription_items",
                "ordering": ["prescription", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["tenant", "patient", "issued_at"], name="rx_tenant_patient_issued_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["tenant", "doctor", "issued_at"], name="rx_tenant_doctor_issued_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(fields=["tenant", "status"], name="rx_tenant_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="prescription",
            constraint=models.UniqueConstraint(
                fields=("tenant", "folio"), name="prescription_tenant_folio_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionitem",
            index=models.Index(
                fields=["prescription", "order"], name="rx_item_prescription_order_idx"
            ),
        ),
    ]
