# Generated by Django 5.2.14 on 2026-06-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0004_rls_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalmedication",
            name="controlled_group",
            field=models.CharField(
                choices=[
                    ("none", "No controlado"),
                    ("I", "Grupo I"),
                    ("II", "Grupo II"),
                    ("III", "Grupo III"),
                    ("IV", "Grupo IV"),
                    ("V", "Grupo V"),
                ],
                db_index=True,
                default="none",
                help_text="Grupo COFEPRIS de medicamento controlado (none = no controlado). Grupos I–V según LGS. Módulo de controlados F6 lo usa para aplicar reglas de vigencia y folio autorizado.",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="globalmedication",
            name="kind",
            field=models.CharField(
                choices=[
                    ("medicamento", "Medicamento"),
                    ("suero", "Suero / solución parenteral"),
                    ("terapia", "Terapia / procedimiento"),
                ],
                db_index=True,
                default="medicamento",
                help_text="Tipo de ítem del catálogo: medicamento, suero o terapia. El seed inicial (313 entradas) mantiene 'medicamento'. COFEPRIS F2.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="controlled_group",
            field=models.CharField(
                choices=[
                    ("none", "No controlado"),
                    ("I", "Grupo I"),
                    ("II", "Grupo II"),
                    ("III", "Grupo III"),
                    ("IV", "Grupo IV"),
                    ("V", "Grupo V"),
                ],
                db_index=True,
                default="none",
                help_text="Grupo COFEPRIS de medicamento controlado (none = no controlado). Módulo de controlados F6.",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="kind",
            field=models.CharField(
                choices=[
                    ("medicamento", "Medicamento"),
                    ("suero", "Suero / solución parenteral"),
                    ("terapia", "Terapia / procedimiento"),
                ],
                db_index=True,
                default="medicamento",
                help_text="Tipo de ítem: medicamento, suero o terapia. Permite catálogos custom de sueros y terapias. COFEPRIS F2.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="diagnosis",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Diagnóstico del paciente al momento de la receta (COFEPRIS F2). COFEPRIS marca 'receta sin diagnóstico' como error que invalida el documento. Texto libre; FK opcional a expediente.Diagnosis = fase futura. No incluir en la receta datos de otro paciente (NOM-024).",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="dose",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Dosis sin abreviaturas (COFEPRIS F2). Ej: '1 tableta', '500 miligramos', '10 mililitros'. Obligatorio para kind=medicamento.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="duration",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Duración del tratamiento sin abreviaturas (COFEPRIS F2). Ej: '7 días', 'hasta terminar el frasco', 'uso crónico'. Obligatorio para kind=medicamento.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="frequency",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Frecuencia de administración sin abreviaturas (COFEPRIS F2). Ej: 'cada 8 horas', 'dos veces al día', 'una vez en ayunas'. Obligatorio para kind=medicamento.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("medicamento", "Medicamento"),
                    ("suero", "Suero / solución parenteral"),
                    ("terapia", "Terapia / procedimiento"),
                ],
                db_index=True,
                default="medicamento",
                help_text="Tipo de ítem: medicamento, suero o terapia. Determina qué campos son obligatorios (validación condicional COFEPRIS). COFEPRIS F2.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="route",
            field=models.CharField(
                blank=True,
                choices=[
                    ("oral", "Oral"),
                    ("sublingual", "Sublingual"),
                    ("intravenosa", "Intravenosa"),
                    ("intramuscular", "Intramuscular"),
                    ("subcutanea", "Subcutánea"),
                    ("topica", "Tópica"),
                    ("oftalmica", "Oftálmica"),
                    ("otica", "Ótica"),
                    ("nasal", "Nasal"),
                    ("rectal", "Rectal"),
                    ("vaginal", "Vaginal"),
                    ("inhalada", "Inhalada"),
                    ("transdermica", "Transdérmica"),
                    ("otra", "Otra"),
                ],
                default="",
                help_text="Vía de administración (COFEPRIS F2). Obligatorio para kind=medicamento. Siempre validado contra choices.",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionitem",
            name="indication",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Nota u observación adicional del médico (opcional). El renglón estructurado (dose/frequency/route/duration) es la fuente COFEPRIS; este campo permite texto libre adicional. En recetas pre-F2 puede contener la indicación completa por compatibilidad.",
            ),
        ),
    ]
