# Generated by Django 5.2.14 on 2026-06-18 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0005_initial"),
        ("recetas", "0005_f2_cofepris_fields"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionFormat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del formato. Ej: 'Estándar clínica', 'Compacta Camsa'.",
                        max_length=120,
                    ),
                ),
                (
                    "base_layout",
                    models.CharField(
                        choices=[
                            ("standard", "Estándar (carta vertical)"),
                            ("compact", "Compacta (media carta horizontal)"),
                            ("digital", "Digital (para el paciente)"),
                        ],
                        db_index=True,
                        default="standard",
                        help_text="Plantilla base del PDF (determina tamaño y estructura del layout).",
                        max_length=10,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#9A7B1E",
                        help_text="Color de acento en hex (#RRGGBB). Se inyecta como variable Django en el template — NO como CSS var() (xhtml2pdf no soporta custom properties).",
                        max_length=7,
                    ),
                ),
                (
                    "font",
                    models.CharField(
                        choices=[
                            ("helvetica", "Helvetica / Arial (sans-serif)"),
                            ("times", "Times New Roman (serif)"),
                        ],
                        default="helvetica",
                        help_text="Tipografía del PDF. Solo fuentes base (Helvetica/Times); fase futura: embeber TTF.",
                        max_length=10,
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        default=dict,
                        help_text="Flags booleanos de secciones opcionales. Whitelist: signos, diagnostico, sueros, terapias, indicaciones. medicamentos siempre está presente. Ejemplo: {signos: true, diagnostico: true, sueros: false, ...}.",
                    ),
                ),
                (
                    "letterhead_mode",
                    models.CharField(
                        choices=[
                            ("digital", "Digital (el sistema imprime el encabezado)"),
                            ("preprinted", "Pre-impreso (deja espacio superior)"),
                        ],
                        default="digital",
                        help_text="Modo de membrete: 'digital' = el sistema imprime el encabezado; 'preprinted' = el médico usa papel pre-impreso (se deja espacio superior).",
                        max_length=12,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True = se aplica automáticamente a todas las recetas del tenant cuando no hay formato por médico. Solo uno puede ser default por tenant. El servicio prescription_format_set_default desmarca el anterior.",
                    ),
                ),
                (
                    "is_authorized",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True = el formato personal del médico está autorizado y se aplica a sus recetas. Solo owner/admin puede cambiar este flag. Irrelevante si doctor es null.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = formato dado de baja (baja lógica). No aparece en selects normales.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Médico propietario del formato (opcional). Si se establece, es el formato personal de ese médico. Se aplica a sus recetas solo si is_authorized=True.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescription_formats",
                        to="personal.doctor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "recetas_prescription_formats",
                "ordering": ["-is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_default", "is_active"],
                        name="pf_tenant_default_active_idx",
                    ),
                    models.Index(
                        fields=["tenant", "doctor", "is_authorized"],
                        name="pf_tenant_doctor_auth_idx",
                    ),
                ],
            },
        ),
    ]
