# Generated by Django 5.2.14 on 2026-06-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0007_rls_prescription_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptionformat",
            name="sections",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flags booleanos de secciones opcionales. Whitelist: signos, diagnostico, sueros, terapias, indicaciones. medicamentos siempre está presente. Ejemplo: {signos: true, diagnostico: true, sueros: false, ...}.",
            ),
        ),
    ]
