# Generated by Django 5.2.15 on 2026-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0008_f3_sections_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="controlled_folio",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Folio del recetario especial que el médico ingresa manualmente (F6). Emitido por COFEPRIS fuera del sistema. Requerido cuando la receta contiene al menos un medicamento controlado (is_controlled=True). Máximo 60 caracteres.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="valid_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Vigencia de la receta, calculada automáticamente al crear (F6). Null para recetas sin medicamentos controlados. Grupo I → 24 horas desde issued_at. Grupo II–V → 30 días desde issued_at (configurable en settings).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="controlled_group",
            field=models.CharField(
                choices=[
                    ("none", "No controlado"),
                    ("I", "Grupo I"),
                    ("II", "Grupo II"),
                    ("III", "Grupo III"),
                    ("IV", "Grupo IV"),
                    ("V", "Grupo V"),
                ],
                db_index=True,
                default="none",
                help_text="Snapshot del grupo COFEPRIS del medicamento al momento de emitir la receta (F6). DR-7: capturado del catálogo al crear — no depende del catálogo futuro. none = no controlado. I–V = grupos según LGS.",
                max_length=5,
            ),
        ),
    ]
