# Generated by Django 5.2.15 on 2026-06-22 20:31
# Editado manualmente: agrega migración de datos para mover base_layout="standard" → "digital"
# antes de eliminar el choice "standard" del campo.

from django.db import migrations, models


def migrate_standard_to_digital(apps, schema_editor):
    """Migra PrescriptionFormat con base_layout='standard' a 'digital'.

    'standard' se elimina como choice válido. Los formatos existentes con ese
    valor se convierten a 'digital' (hoja completa para el paciente), que es la
    alternativa semánticamente equivalente.
    """
    PrescriptionFormat = apps.get_model("recetas", "PrescriptionFormat")
    PrescriptionFormat.objects.filter(base_layout="standard").update(
        base_layout="digital"
    )


def reverse_digital_to_standard(apps, schema_editor):
    """Reversión: no es posible distinguir qué 'digital' era originalmente 'standard'.

    Como medida segura, no tocamos los 'digital' existentes. La migración es
    reversible en el sentido de que no se pierden datos (los registros quedan en
    'digital', que es un valor válido en la migración anterior).
    """
    pass  # reversión segura: no hay forma de distinguir el origen


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0009_f6_controlled_fields"),
    ]

    operations = [
        # 1. Primero migrar datos: standard → digital (antes de que el choice desaparezca)
        migrations.RunPython(
            migrate_standard_to_digital,
            reverse_code=reverse_digital_to_standard,
        ),
        # 2. Luego alterar el campo (elimina el choice "standard", cambia default a "digital")
        migrations.AlterField(
            model_name="prescriptionformat",
            name="base_layout",
            field=models.CharField(
                choices=[
                    ("compact", "Farmacia (media carta)"),
                    ("digital", "Paciente (hoja completa)"),
                ],
                db_index=True,
                default="digital",
                help_text="Plantilla base del PDF: 'digital' = hoja completa (paciente); 'compact' = media carta (farmacia).",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionformat",
            name="sections",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flags booleanos de secciones opcionales. Whitelist (10 claves): signos, edad_sexo, diagnostico, alergias, sueros, terapias, indicaciones, vigencia, contacto_clinica, qr. medicamentos siempre está presente. Claves omitidas reciben True por defecto vía get_sections_full().",
            ),
        ),
    ]
