# Generated by Django 5.2.15 on 2026-06-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0010_reduce_formats_and_expand_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionformat",
            name="theme",
            field=models.CharField(
                choices=[
                    ("ondas", "Ondas suaves"),
                    ("minimal", "Minimalista"),
                    ("marco", "Marco elegante"),
                    ("barra", "Barra lateral"),
                    ("banda", "Banda superior"),
                    ("geometrico", "Geométrico"),
                ],
                default="ondas",
                help_text="Estilo decorativo del fondo/marco del PDF (no cambia la estructura).",
                max_length=12,
            ),
        ),
    ]
