# Generated by Django 5.2.15 on 2026-06-23 16:01

from django.db import migrations, models


def _marco_to_ondas(apps, schema_editor):
    """El estilo 'marco' se retiró: los formatos que lo usaban pasan a 'ondas'."""
    PrescriptionFormat = apps.get_model("recetas", "PrescriptionFormat")
    PrescriptionFormat.objects.filter(theme="marco").update(theme="ondas")


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0012_alter_prescriptionformat_theme"),
    ]

    operations = [
        migrations.RunPython(_marco_to_ondas, _noop),
        migrations.AlterField(
            model_name="prescriptionformat",
            name="theme",
            field=models.CharField(
                choices=[
                    ("ondas", "Ondas suaves"),
                    ("minimal", "Minimalista"),
                    ("barra", "Barra lateral"),
                    ("geometrico", "Geométrico"),
                ],
                default="ondas",
                help_text="Estilo decorativo del fondo/marco del PDF (no cambia la estructura).",
                max_length=12,
            ),
        ),
    ]
