# Generated by Django 5.2.15 on 2026-06-29 17:40

import apps.recetas.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0013_alter_prescriptionformat_theme"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionPdfJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                ("cache_key", models.CharField(max_length=200)),
                ("layout", models.CharField(blank=True, default="", max_length=40)),
                ("format_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("done", "Listo"),
                            ("failed", "Falló"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="PDF generado; None hasta que la tarea termina.",
                        null=True,
                        upload_to=apps.recetas.models.prescription_pdf_path,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        help_text="Receta cuyo PDF se genera.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_jobs",
                        to="recetas.prescription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "recetas_prescription_pdf_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "prescription"], name="presc_pdf_job_presc_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "cache_key"), name="prescription_pdf_job_cache_uniq"
                    )
                ],
            },
        ),
    ]
