# Generated by Django 5.2.15 on 2026-07-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0015_rls_prescription_pdf_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="medication_commercial_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Denominación DISTINTIVA (comercial) del medicamento (snapshot, OPCIONAL). Se imprime como secundaria; el genérico manda (Art. 83 LGS).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionitem",
            name="medication_name",
            field=models.CharField(
                help_text="Denominación GENÉRICA del medicamento (snapshot al crear). REQUERIDA por el Art. 83 LGS / NOM-004: el genérico se imprime primero. Es la fuente de verdad inmutable del documento. DR-7: el catálogo puede cambiar; la receta no.",
                max_length=200,
            ),
        ),
    ]
