# Generated by Django 5.2.15 on 2026-07-02 15:43

import apps.recetas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0016_prescriptionitem_medication_commercial_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptionpdfjob",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="PDF generado; None hasta que la tarea termina.",
                max_length=255,
                null=True,
                upload_to=apps.recetas.models.prescription_pdf_path,
            ),
        ),
    ]
