# Generated by Django 5.2.14 on 2026-06-16 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0002_enable_rls"),
        ("pacientes", "0008_merge_20260616_1224"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "heredo_familiares",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Antecedentes heredo-familiares (AHF). Claves del schema: numero_hermanos (int), diabetes, hipertension_arterial, cardiopatias, hepatopatias, urologicos, neurologicos, respiratorias, cancer, alergicas, metabolicas, sanguineas, articulares, inmunologicas, malformaciones, dermatologicas, otros (strings, default 'Negado').",
                    ),
                ),
                (
                    "personales_patologicos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Antecedentes personales patológicos (APP). NO incluye alergias (fuente de verdad: modelo Allergy). Strings con default 'Negado': enfermedades_infancia, diabetes, hipertension, respiratorias, oftalmico, cardiovasculares, neurologicos, gastrointestinales, hepatopatias, metabolicas, urologicos, circulatorio, traumaticas, articulares, dermatologicas, quirurgicos, transfusionales, vectores, autoinmunes, emocionales, adicciones, hospitalizaciones_previas, pesticidas, dx_cancer, otros.",
                    ),
                ),
                (
                    "no_patologicos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Antecedentes personales no patológicos (APNP) — núcleo universal. Lo dental se mueve a la extensión Odontología (plan §3.2). Claves: casa_habitacion (choices), servicios_basicos, actividad_fisica, tabaquismo, alcoholismo, otras_toxicomanias, inmunizaciones, ultima_desparasitacion, otros.",
                    ),
                ),
                (
                    "habitos_alimenticios",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Hábitos alimenticios — versión corta del núcleo. La encuesta de 32 alimentos va a la extensión Nutrición. Claves: numero_comidas_dia (int), dieta_especial, intolerancias_alimentarias, consumo_agua_litros, suplementos.",
                    ),
                ),
                (
                    "gineco_obstetricos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Antecedentes gineco-obstétricos (AGO). Solo aplica a pacientes de sexo F; el serializer rechaza contenido no vacío para sexos M/X (validación condicional por sexo). Claves: menarca, ritmo_menstrual, alteraciones, fum, ivsa, numero_parejas, gestas, abortos, partos, cesareas, fup, metodo_planificacion, citologia_vaginal, colposcopia, usg_pelvico, mastografia, usg_mamas, menopausia_climaterio, tratamientos_hormonales.",
                    ),
                ),
                (
                    "exploracion_fisica_basal",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Exploración física basal por sistema/aparato. Estructura: { 'sistema': { 'estado': <sin_alteraciones|con_alteraciones>, 'detalle': <str> } }. Sistemas permitidos: cerebro, sistema_nervioso, ocular, endocrino, corazon, circulatorio, respiratorio, hepatico, pancreas, renal, gastrointestinal, osteoarticular, tendomuscular, reproductor, inmunologico, extremidades, piel_tegumentos, otros.",
                    ),
                ),
                (
                    "antecedentes_importancia",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Antecedentes de importancia (texto libre).",
                    ),
                ),
                (
                    "padecimiento_actual",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Padecimiento actual del paciente (texto libre).",
                    ),
                ),
                (
                    "tratamientos_actuales",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Tratamientos actuales del paciente (texto libre).",
                    ),
                ),
                (
                    "prioridad_analisis",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Prioridades de análisis clínico (texto libre).",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Paciente al que pertenece la historia clínica.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_histories",
                        to="pacientes.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_medical_histories",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["patient"], name="medical_history_patient_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("patient",),
                        name="medical_history_patient_active_uniq",
                    )
                ],
            },
        ),
    ]
