# Generated by Django 5.2.14 on 2026-06-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0007_rls_vital_signs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalsignsrecord",
            name="extra_params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Parámetros del legacy. Claves permitidas (EXTRA_PARAMS_WHITELIST): colesterol, trigliceridos, urea, creatinina, hemoglobina. Todos deben ser numéricos positivos. El serializer rechaza claves no declaradas (D-EC-7).",
            ),
        ),
    ]
