# Generated by Django 5.2.14 on 2026-06-16 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0010_appointment_reschedule_count"),
        ("expediente", "0008_alter_vitalsignsrecord_extra_params"),
        ("pacientes", "0008_merge_20260616_1224"),
        ("personal", "0004_doctor_consultorios"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvolutionNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "antecedentes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Antecedentes de importancia del episodio.",
                    ),
                ),
                (
                    "interrogatorio",
                    models.TextField(
                        blank=True, default="", help_text="Interrogatorio por aparatos y sistemas."
                    ),
                ),
                (
                    "estudios",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Estudios solicitados o reportados en la consulta.",
                    ),
                ),
                (
                    "diagnosticos_texto",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Diagnósticos en texto libre (complementa el modelo Diagnosis).",
                    ),
                ),
                (
                    "tratamiento",
                    models.TextField(
                        blank=True, default="", help_text="Tratamiento prescrito en la consulta."
                    ),
                ),
                (
                    "plan_recomendaciones",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Plan de seguimiento y recomendaciones al paciente.",
                    ),
                ),
                (
                    "indicaciones_enfermeria",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Indicaciones específicas para el personal de enfermería.",
                    ),
                ),
                (
                    "exploracion_fisica",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Exploración física por aparatos/sistema. Estructura: { '<sistema>': { 'estado': <estado_semaforo>, 'detalle': <str> } }. Estados: no_evaluado (default), normal, observacion, alterado. Sistemas = misma lista que exploracion_fisica_basal de MedicalHistory.",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=True,
                        help_text="True = nota firmada (inmutable). Se establece True al crear y nunca cambia. No existe endpoint para desbloquear (D-EC-1).",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        help_text="Cita médica de la que nace esta evolución. Debe estar en estado ATTENDED y pertenecer al mismo paciente y tenant (D-EC-2).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evolution_notes",
                        to="agenda.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Médico autor clínico de la nota (debe ser el doctor de la cita).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evolution_notes",
                        to="personal.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Paciente al que pertenece la nota de evolución.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evolution_notes",
                        to="pacientes.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "vital_signs",
                    models.ForeignKey(
                        blank=True,
                        help_text="Toma de signos vitales asociada (opcional). Si se provee, debe pertenecer al mismo paciente y tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evolution_notes",
                        to="expediente.vitalsignsrecord",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_evolution_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "cie_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código CIE-10 (texto libre en v1; catálogo formal en versiones futuras).",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Descripción del diagnóstico (requerida, no puede estar vacía).",
                        max_length=255,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("presuntivo", "Presuntivo"), ("definitivo", "Definitivo")],
                        default="presuntivo",
                        help_text="Tipo de diagnóstico: presuntivo (default) o definitivo.",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("activo", "Activo"), ("resuelto", "Resuelto")],
                        db_index=True,
                        default="activo",
                        help_text="Estado del diagnóstico: activo (default) o resuelto (baja lógica).",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Paciente al que pertenece el diagnóstico.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnoses",
                        to="pacientes.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "evolution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nota de evolución donde se asentó el diagnóstico (opcional). Si se provee, debe pertenecer al mismo paciente y tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnoses",
                        to="expediente.evolutionnote",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_diagnoses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Addendum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Texto del addendum (requerido, no puede estar vacío)."
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Usuario que agrega el addendum.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addenda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "evolution",
                    models.ForeignKey(
                        help_text="Nota de evolución a la que se agrega este addendum.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addenda",
                        to="expediente.evolutionnote",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_addenda",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="evolutionnote",
            index=models.Index(
                fields=["tenant", "patient", "created_at"], name="evol_tenant_patient_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosis",
            index=models.Index(
                fields=["tenant", "patient", "status"], name="diag_tenant_patient_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="addendum",
            index=models.Index(
                fields=["tenant", "evolution", "created_at"], name="addendum_evol_time_idx"
            ),
        ),
    ]
