# Generated by Django 5.2.14 on 2026-06-16 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0010_appointment_reschedule_count"),
        ("expediente", "0010_rls_evolution_addendum_diagnosis"),
        ("pacientes", "0008_merge_20260616_1224"),
        ("personal", "0004_doctor_consultorios"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="evolutionnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("appointment",),
                name="evolution_note_appointment_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="evolutionnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_locked", True)), name="evolution_is_locked_always"
            ),
        ),
    ]
