# Generated by Django 5.2.15 on 2026-06-25 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0013_rls_evolution_images"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalhistory",
            name="custom_answers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Respuestas a preguntas extra configurables por la clínica (Fase 2). Estructura: {"<question_uuid>": <valor>}. Las claves son UUIDs de MedicalHistoryQuestion activas del mismo tenant. Las claves que no correspondan a preguntas activas se ignoran silenciosamente.',
            ),
        ),
        migrations.CreateModel(
            name="MedicalHistoryQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Texto de la pregunta visible en el formulario clínico.",
                        max_length=255,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto corto"),
                            ("textarea", "Texto largo"),
                            ("boolean", "Sí / No"),
                            ("select", "Selección única"),
                            ("number", "Número"),
                            ("date", "Fecha"),
                        ],
                        help_text="Tipo de campo de captura.",
                        max_length=12,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de opciones para field_type='select'. Debe ser lista no vacía de strings cuando field_type=select. Debe ser lista vacía para todos los demás tipos.",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Agrupador opcional (ej. 'Antecedentes extras', 'Datos socioeconómicos').",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Posición en el formulario. Menor número = aparece primero.",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Si True, el frontend debe exigir respuesta antes de guardar la HC.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="True = pregunta activa (visible en el formulario). False = baja lógica (no se muestra en nuevas capturas, las respuestas históricas permanecen).",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_medical_history_questions",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(fields=["tenant", "is_active"], name="mhq_tenant_active_idx")
                ],
            },
        ),
    ]
