# Generated by Django 5.2.15 on 2026-07-02 15:43

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0015_rls_medical_history_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evolutionimage",
            name="image",
            field=models.ImageField(
                help_text="Imagen clínica (JPEG/PNG/WEBP, máx 10 MB). El nombre se aleatoriza al guardar (anti path-traversal).",
                max_length=255,
                upload_to=apps.core.files.evolution_image_path,
            ),
        ),
    ]
