# Generated by Django 5.2.15 on 2026-07-08 15:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0016_alter_evolutionimage_image"),
        ("pacientes", "0014_rls_with_check"),
        ("personal", "0007_rls_with_check"),
        ("tenancy", "0005_seed_plans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "identificacion",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Identificación del paciente al momento de la consulta (sexo, edad).",
                    ),
                ),
                (
                    "antecedentes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Antecedentes relevantes (heredofamiliares y personales patológicos).",
                    ),
                ),
                (
                    "padecimiento_actual",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Motivo de la consulta / padecimiento actual.",
                    ),
                ),
                (
                    "exploracion_fisica",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Hallazgos relevantes de la exploración física.",
                    ),
                ),
                (
                    "diagnostico_manejo",
                    models.TextField(
                        blank=True, default="", help_text="Diagnóstico(s) y manejo indicado."
                    ),
                ),
                (
                    "indicaciones",
                    models.TextField(
                        blank=True, default="", help_text="Indicaciones entregadas al paciente."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que generó el resumen (auditoría).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_summaries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Médico de la evolución (snapshot para el membrete del PDF).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_summaries",
                        to="personal.doctor",
                    ),
                ),
                (
                    "evolution",
                    models.ForeignKey(
                        help_text="Nota de evolución (consulta) de la que nace este resumen.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_summaries",
                        to="expediente.evolutionnote",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Paciente al que pertenece el resumen clínico.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_summaries",
                        to="pacientes.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_clinical_summaries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "patient", "created_at"],
                        name="clin_summ_tenant_pat_time_idx",
                    )
                ],
            },
        ),
    ]
