# Generated by Django 5.2.15 on 2026-07-08 16:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0018_rls_clinical_summaries"),
        ("finanzas", "0003_rls_with_check"),
        ("pacientes", "0014_rls_with_check"),
        ("personal", "0007_rls_with_check"),
        ("tenancy", "0005_seed_plans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="Esquema y aplicación de protocolos de tratamientos",
                        help_text="Título visible del documento (banda de título del PDF).",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notas libres del esquema (no se imprimen en el PDF v1).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("activa", "Activa"),
                            ("completada", "Completada"),
                        ],
                        db_index=True,
                        default="activa",
                        help_text="Estado del esquema: borrador, activa o completada.",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que generó/guardó el esquema (auditoría).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Médico responsable del esquema (opcional).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_plans",
                        to="personal.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Paciente al que pertenece el esquema de tratamientos.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_plans",
                        to="pacientes.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_treatment_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentPlanItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Nombre del tratamiento (snapshot del concepto al crearse; editable).",
                        max_length=255,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Precio unitario del tratamiento (snapshot).",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Número de sesiones del tratamiento."
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Posición de la línea en la tabla del esquema."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Esquema al que pertenece esta línea de tratamiento.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="expediente.treatmentplan",
                    ),
                ),
                (
                    "service_concept",
                    models.ForeignKey(
                        blank=True,
                        help_text="Concepto del catálogo (opcional; permite captura manual).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="finanzas.serviceconcept",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_treatment_plan_items",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Número de sesión dentro del tratamiento (1..N)."
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, help_text="Fecha programada de la sesión.", null=True
                    ),
                ),
                (
                    "applied_date",
                    models.DateField(
                        blank=True, help_text="Fecha en que se aplicó la sesión.", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("programada", "Programada"), ("aplicada", "Aplicada")],
                        db_index=True,
                        default="programada",
                        help_text="Estado de la sesión: programada o aplicada.",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="Línea de tratamiento a la que pertenece esta sesión.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="expediente.treatmentplanitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_treatment_sessions",
                "ordering": ["number", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="treatmentplan",
            index=models.Index(
                fields=["tenant", "patient", "created_at"], name="tx_plan_tenant_pat_time_idx"
            ),
        ),
    ]
