# Generated by Django 5.2.15 on 2026-07-08 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0013_rls_with_check"),
        ("expediente", "0020_rls_treatment_plans"),
        ("personal", "0007_rls_with_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentplan",
            name="consultorio",
            field=models.ForeignKey(
                blank=True,
                help_text="Consultorio por defecto del esquema, usado al agendar sus sesiones (opcional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="personal.consultorio",
            ),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Cita real de agenda ligada a esta sesión, si ya se agendó.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatment_sessions",
                to="agenda.appointment",
            ),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Duración de la cita agendada, en minutos. Null = usa el default del médico.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="treatmentsession",
            name="scheduled_time",
            field=models.TimeField(
                blank=True,
                help_text="Hora local programada de la sesión (complementa scheduled_date).",
                null=True,
            ),
        ),
    ]
