# Generated by Django 5.2.15 on 2026-07-08 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0021_add_treatment_calendarizacion_scheduling"),
        ("finanzas", "0003_rls_with_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentplan",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                help_text="Cotización (borrador) generada a partir de este esquema (Fase 2 — Calendarización), si existe. Cada regeneración crea una cotización NUEVA y reapunta este campo; la anterior no se borra.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finanzas.quote",
            ),
        ),
    ]
