# Generated by Django 5.2.15 on 2026-07-10 16:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expediente", "0022_treatmentplan_quote"),
        ("pacientes", "0014_rls_with_check"),
        ("personal", "0007_rls_with_check"),
        ("tenancy", "0005_seed_plans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LongevityPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "alergias",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Alergias vigentes del paciente (snapshot editable).",
                    ),
                ),
                (
                    "antecedentes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Antecedentes de importancia (snapshot editable de la HC).",
                    ),
                ),
                (
                    "tratamientos_actuales",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Tratamientos actuales del paciente (snapshot editable de la HC).",
                    ),
                ),
                (
                    "condiciones_mejorar",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Principales condiciones a mejorar (sugeridas desde la exploración física basal).",
                    ),
                ),
                (
                    "estudios",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reporte de estudios de laboratorio y gabinete.",
                    ),
                ),
                (
                    "reporte_medico",
                    models.TextField(blank=True, default="", help_text="Reporte médico."),
                ),
                (
                    "interconsulta",
                    models.TextField(
                        blank=True, default="", help_text="Interconsulta de departamentos."
                    ),
                ),
                (
                    "seguimiento",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Seguimiento y acompañamiento propuesto al paciente.",
                    ),
                ),
                (
                    "esquema",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Snapshot de los tratamientos del treatment_plan al momento de crear la constancia: [{description, quantity, clinical_description}]. Lista vacía si no se ligó ningún esquema.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que generó el plan (auditoría).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="longevity_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Médico que genera el plan (si el actor es médico; None si es owner/admin).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="longevity_plans",
                        to="personal.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Paciente al que pertenece el Plan Integral de Longevidad.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="longevity_plans",
                        to="pacientes.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "treatment_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Esquema de calendarización de tratamientos usado como base del snapshot `esquema` (opcional). Si se borra o cambia después, `esquema` conserva los valores con los que se creó esta constancia.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="longevity_plans",
                        to="expediente.treatmentplan",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_longevity_plans",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "patient", "created_at"],
                        name="long_plan_tenant_pat_time_idx",
                    )
                ],
            },
        ),
    ]
