# Generated by Django 5.2.15 on 2026-07-10
"""Crea DocumentTemplate — catálogo de plantillas de documento (Fase 2)."""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expediente", "0024_rls_longevity_plans"),
        ("tenancy", "0005_seed_plans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre identificador de la plantilla.", max_length=160
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("reporte_medico", "Reporte médico"),
                            ("seguimiento", "Seguimiento"),
                            ("interconsulta", "Interconsulta"),
                            ("estudios", "Estudios"),
                            ("condiciones_mejorar", "Condiciones a mejorar"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        help_text="Sección del Plan Integral a la que está destinada esta plantilla.",
                        max_length=30,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Cuerpo de la plantilla. Texto libre que el médico copia/edita."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text=(
                            "False = plantilla oculta del catálogo (no aparece en el "
                            "listado por defecto)."
                        ),
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Usuario que creó el registro. Null en imports/seeds o si el "
                            "usuario fue borrado."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_document_templates",
                "ordering": ["section", "name"],
                "indexes": [
                    models.Index(fields=["tenant", "section"], name="doc_tmpl_tenant_section_idx")
                ],
            },
        ),
    ]
