# Generated by Django 5.2.15 on 2026-07-10
"""Crea LabAnalyte — catálogo de analitos de laboratorio (Fase 3)."""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expediente", "0026_rls_document_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabAnalyte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del analito (p. ej. 'Glucosa en ayuno', 'Colesterol total').",
                        max_length=160,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unidad de medida (p. ej. 'mg/dL').",
                        max_length=40,
                    ),
                ),
                (
                    "ref_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Límite inferior del rango de referencia (opcional).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "ref_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Límite superior del rango de referencia (opcional).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text=(
                            "False = analito oculto del catálogo (no aparece en el "
                            "listado por defecto)."
                        ),
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Usuario que creó el registro. Null en imports/seeds o si el "
                            "usuario fue borrado."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "expediente_lab_analytes",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["tenant", "name"], name="lab_analyte_tenant_name_idx")
                ],
            },
        ),
    ]
