# Generated by Django 5.2.15 on 2026-07-10
"""
Agrega lab_results y gabinete_studies a LongevityPlan (Fase 3, punto 2).

Solo AddField — expediente_longevity_plans ya tiene RLS habilitado desde
0024_rls_longevity_plans.py y no requiere una nueva migración de RLS.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expediente", "0028_rls_lab_analytes"),
    ]

    operations = [
        migrations.AddField(
            model_name="longevityplan",
            name="lab_results",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Snapshot de resultados de laboratorio capturados al crear la "
                    "constancia: [{analyte_id, name, unit, ref_low, ref_high, result, "
                    "out_of_range}]. out_of_range se calcula en longevity_plan_create "
                    "contra el rango de referencia vigente del analito (o el capturado "
                    "a mano) al momento de crear."
                ),
            ),
        ),
        migrations.AddField(
            model_name="longevityplan",
            name="gabinete_studies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Snapshot de estudios de gabinete capturados al crear la "
                    "constancia: [{name, conclusion}]."
                ),
            ),
        ),
    ]
