# Generated by Django 5.2.15 on 2026-07-10
"""
Agrega equipo a LongevityPlan (Fase 4, punto 2).

Solo AddField — expediente_longevity_plans ya tiene RLS habilitado desde
0024_rls_longevity_plans.py y no requiere una nueva migración de RLS.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expediente", "0029_longevityplan_lab_gabinete"),
    ]

    operations = [
        migrations.AddField(
            model_name="longevityplan",
            name="equipo",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Snapshot del equipo/departamentos de la clínica al momento de "
                    "crear la constancia (config-driven, NO lo envía el cliente): "
                    "[{departamento, nombre}], tomado de apps.clinica.ClinicTeamMember."
                ),
            ),
        ),
    ]
