# Generated by Django 5.2.14 on 2026-06-02 14:28

import apps.authn.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Dirección de correo electrónico. Usado como nombre de usuario.', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar en lugar de borrar para preservar historial.')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite acceder al Django Admin. NO implica ser staff de plataforma.')),
                ('is_platform_staff', models.BooleanField(db_index=True, default=False, help_text='True = pertenece al equipo interno de Maily Soft.')),
                ('platform_role', models.CharField(blank=True, choices=[('super_admin', 'Súper Admin'), ('sales', 'Ventas / Éxito de Cliente'), ('engineering', 'Ingeniería')], default='', help_text='Rol dentro del equipo de plataforma. Ignorado si is_platform_staff=False.', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'authn_users',
                'ordering': ['email'],
            },
            managers=[
                ('objects', apps.authn.managers.UserManager()),
            ],
        ),
    ]
