# Generated by Django 5.2.14 on 2026-06-09 16:34

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil del usuario (opcional).",
                null=True,
                upload_to=apps.core.files.user_avatar_path,
            ),
        ),
    ]
