# Generated by Django 5.2.15 on 2026-07-02 15:43

import apps.core.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil del usuario (opcional).",
                max_length=255,
                null=True,
                upload_to=apps.core.files.user_avatar_path,
            ),
        ),
    ]
