# Generated by Django 5.2.15 on 2026-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="True obliga a cambiar la contraseña en el próximo request de negocio (POST /api/v1/auth/change-password/ la limpia). Se activa al recibir una contraseña temporal: alta de clínica (dueño) o alta de staff de plataforma. Los usuarios de seed la dejan explícitamente en False.",
            ),
        ),
    ]
