# Generated by Django 5.2.14 on 2026-06-05 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "actor_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot del rol del actor en el momento del evento.",
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("PATIENT_CREATE", "Crear paciente"),
                            ("PATIENT_READ", "Leer ficha de paciente"),
                            ("PATIENT_UPDATE", "Actualizar paciente"),
                            ("PATIENT_DEACTIVATE", "Desactivar paciente"),
                            ("APPOINTMENT_CREATE", "Crear cita"),
                            ("APPOINTMENT_UPDATE", "Actualizar cita"),
                            ("APPOINTMENT_STATUS", "Cambiar estado de cita"),
                            ("APPOINTMENT_RESCHEDULE", "Reagendar cita"),
                            ("DOCTOR_CREATE", "Crear médico"),
                            ("DOCTOR_UPDATE", "Actualizar médico"),
                            ("DOCTOR_DEACTIVATE", "Desactivar médico"),
                            ("CONSULTORIO_CREATE", "Crear consultorio"),
                            ("CONSULTORIO_UPDATE", "Actualizar consultorio"),
                            ("CONSULTORIO_DEACTIVATE", "Desactivar consultorio"),
                            ("SCHEDULE_CREATE", "Crear horario"),
                            ("SCHEDULE_DEACTIVATE", "Desactivar horario"),
                            ("CONFIG_UPDATE", "Actualizar configuración de agenda"),
                            ("LOGIN", "Inicio de sesión"),
                            ("LOGIN_FAILED", "Intento de sesión fallido"),
                        ],
                        db_index=True,
                        help_text="Tipo de acción realizada (ActionType).",
                        max_length=30,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text='Nombre del modelo afectado: "Patient", "Appointment", etc.',
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID del objeto afectado (nullable para eventos sin objeto específico).",
                        null=True,
                    ),
                ),
                (
                    "resource_repr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Representación legible del recurso en el momento del evento (snapshot).",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción en lenguaje natural del evento.",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP de origen del request. Puede ser NAT; se registra igual (NOM-024).",
                        null=True,
                        unpack_ipv4=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, default="", help_text="User-Agent del cliente.", max_length=512
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID de correlación del request (X-Request-ID o uuid4 hex generado).",
                        max_length=64,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Contexto adicional SIN PII clínica. Permitido: changed_fields, old/new_status, ids relacionados. Prohibido: diagnósticos, notas clínicas, CURP, teléfono, nombre.",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que realizó la acción. Null si se borró el usuario o evento anónimo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clínica del evento. Null para eventos globales (ej. login fallido sin tenant).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "created_at"], name="audit_tenant_created_idx"),
                    models.Index(fields=["tenant", "actor"], name="audit_tenant_actor_idx"),
                    models.Index(
                        fields=["tenant", "resource_type", "resource_id"],
                        name="audit_tenant_resource_idx",
                    ),
                    models.Index(fields=["tenant", "action"], name="audit_tenant_action_idx"),
                ],
            },
        ),
    ]
