# Generated by Django 5.2.14 on 2026-06-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("PATIENT_CREATE", "Crear paciente"),
                    ("PATIENT_READ", "Leer ficha de paciente"),
                    ("PATIENT_UPDATE", "Actualizar paciente"),
                    ("PATIENT_DEACTIVATE", "Desactivar paciente"),
                    ("APPOINTMENT_CREATE", "Crear cita"),
                    ("APPOINTMENT_UPDATE", "Actualizar cita"),
                    ("APPOINTMENT_STATUS", "Cambiar estado de cita"),
                    ("APPOINTMENT_RESCHEDULE", "Reagendar cita"),
                    ("DOCTOR_CREATE", "Crear médico"),
                    ("DOCTOR_UPDATE", "Actualizar médico"),
                    ("DOCTOR_DEACTIVATE", "Desactivar médico"),
                    ("CONSULTORIO_CREATE", "Crear consultorio"),
                    ("CONSULTORIO_UPDATE", "Actualizar consultorio"),
                    ("CONSULTORIO_DEACTIVATE", "Desactivar consultorio"),
                    ("SCHEDULE_CREATE", "Crear horario"),
                    ("SCHEDULE_DEACTIVATE", "Desactivar horario"),
                    ("CONFIG_UPDATE", "Actualizar configuración de agenda"),
                    ("MEMBER_CREATE", "Alta de miembro"),
                    ("MEMBER_UPDATE", "Actualizar miembro (rol)"),
                    ("MEMBER_BLOCK", "Bloquear o reactivar cuenta de miembro"),
                    ("LOGIN", "Inicio de sesión"),
                    ("LOGOUT", "Cierre de sesión"),
                    ("LOGIN_FAILED", "Intento de sesión fallido"),
                ],
                db_index=True,
                help_text="Tipo de acción realizada (ActionType).",
                max_length=30,
            ),
        ),
    ]
