# Generated by Django 5.2.15 on 2026-06-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_finanzas_action_types"),
        ("audit", "0034_alter_auditlog_action"),
    ]

    operations = []
