# Generated by Django 5.2.14 on 2026-06-02 20:11

import apps.agenda.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0004_alter_patient_record_number"),
        ("personal", "0003_alter_doctor_membership_and_more"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(db_index=True, help_text="Inicio de la cita en UTC."),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        help_text="Fin de la cita en UTC. Debe ser posterior a starts_at."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("confirmed", "Confirmada"),
                            ("arrived", "En sala"),
                            ("in_progress", "En consulta"),
                            ("attended", "Atendida"),
                            ("cancelled", "Cancelada"),
                            ("no_show", "No se presentó"),
                        ],
                        db_index=True,
                        default="scheduled",
                        help_text="Estado actual de la cita. SOLO modificar a través de appointment_change_status en services.py.",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(help_text="Motivo de la cita (requerido).", max_length=255),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Especialidad de la cita. Texto libre en v1; catálogo en v2.",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Notas internas de la cita."
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Motivo de cancelación (se registra al cancelar).",
                    ),
                ),
                (
                    "series_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="UUID de la serie de citas recurrentes. GANCHO v2 — siempre None en v1. No crear tabla AppointmentSeries hasta v2.",
                        null=True,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que canceló la cita.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultorio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Consultorio donde se realizará la cita. Opcional (puede ser telemedicina o domicilio).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="personal.consultorio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Médico que atenderá la cita.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="personal.doctor",
                    ),
                ),
                (
                    "no_show_registered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que registró la inasistencia.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Paciente al que corresponde la cita.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="pacientes.patient",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agenda_appointments",
                "ordering": ["-starts_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "doctor", "starts_at", "ends_at"],
                        name="appt_doctor_range_idx",
                    ),
                    models.Index(
                        fields=["tenant", "consultorio", "starts_at", "ends_at"],
                        name="appt_consultorio_range_idx",
                    ),
                    models.Index(
                        fields=["tenant", "patient", "-starts_at"], name="appt_patient_hist_idx"
                    ),
                    models.Index(fields=["tenant", "status", "starts_at"], name="appt_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantAgendaConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "record_number_format",
                    models.CharField(
                        default="EXP-{year}-{seq:05d}",
                        help_text="Plantilla del número de expediente. Placeholders: {year} (año) y {seq} (consecutivo). Ejemplo: EXP-{year}-{seq:05d}",
                        max_length=50,
                    ),
                ),
                (
                    "record_number_reset_yearly",
                    models.BooleanField(
                        default=False,
                        help_text="Si True, el consecutivo de expediente se reinicia cada año.",
                    ),
                ),
                (
                    "default_appointment_duration",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Duración default de cita en minutos a nivel clínica. Doctor.default_appointment_duration tiene precedencia sobre este valor.",
                    ),
                ),
                (
                    "reminder_offsets_minutes",
                    models.JSONField(
                        default=apps.agenda.models._default_reminder_offsets,
                        help_text="Lista de enteros: minutos antes de la cita para cada recordatorio. Ejemplo: [1440] = 24h, [1440, 120] = 24h y 2h.",
                    ),
                ),
                (
                    "reminders_enabled",
                    models.BooleanField(
                        default=True, help_text="Interruptor global de recordatorios de la clínica."
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agenda_tenant_config",
                "constraints": [
                    models.UniqueConstraint(fields=("tenant",), name="agenda_config_tenant_uniq")
                ],
            },
        ),
    ]
