# Generated by Django 5.2.14 on 2026-06-09 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0005_appointment_reminder_rls"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Motivo de la cita (texto libre, opcional).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentreminder",
            name="message_preview",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Primeros ~500 caracteres del mensaje enviado (para trazabilidad). LFPDPPP: este campo puede contener datos personales del paciente (nombre, fecha de cita). Está protegido por Row Level Security (RLS) en PostgreSQL; nunca exponerlo en listados públicos ni logs. Solo consultable por usuarios del mismo tenant.",
            ),
        ),
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del tipo de cita (ej. 'Primera vez', 'Seguimiento').",
                        max_length=80,
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Color #RRGGBB para distinguir el tipo en la agenda.",
                        max_length=7,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = tipo desactivado (no aparece al agendar).",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agenda_appointment_types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de cita (categoría con color). Opcional.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="agenda.appointmenttype",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmenttype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant", "name"),
                name="appointment_type_name_uniq",
            ),
        ),
    ]
