# Generated by Django 5.2.14 on 2026-06-09 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0006_alter_appointment_reason_and_more"),
        ("personal", "0003_alter_doctor_membership_and_more"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("meeting", "Reunión"), ("block", "Bloqueo")],
                        db_index=True,
                        default="block",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Título del evento (ej. 'Junta', 'Día festivo'). Opcional.",
                        max_length=120,
                    ),
                ),
                ("starts_at", models.DateTimeField(db_index=True, help_text="Inicio en UTC.")),
                (
                    "ends_at",
                    models.DateTimeField(help_text="Fin en UTC. Debe ser posterior a starts_at."),
                ),
                (
                    "all_day",
                    models.BooleanField(default=False, help_text="True = ocupa el día completo."),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "consultorio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Consultorio al que aplica. Null = no atado a un consultorio.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_blocks",
                        to="personal.consultorio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Médico al que aplica. Null = no atado a un médico.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_blocks",
                        to="personal.doctor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agenda_blocks",
                "ordering": ["starts_at"],
            },
        ),
    ]
