# Generated by Django 5.2.14 on 2026-06-09 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0007_agendablock"),
        ("tenancy", "0003_alter_tenantmembership_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaItemNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = activo. Rellenar para borrado lógico.",
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Contenido de la nota. Requerido, no puede estar vacío."
                    ),
                ),
                (
                    "agenda_block",
                    models.ForeignKey(
                        blank=True,
                        help_text="Evento al que pertenece esta nota. Null si pertenece a una cita.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_notes",
                        to="agenda.agendablock",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cita a la que pertenece esta nota. Null si pertenece a un evento.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_notes",
                        to="agenda.appointment",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Usuario que agregó la nota.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_item_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el registro. Null en imports/seeds o si el usuario fue borrado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Clínica a la que pertenece este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agenda_item_notes",
                "ordering": ["created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("agenda_block__isnull", True), ("appointment__isnull", False)
                            ),
                            models.Q(
                                ("agenda_block__isnull", False), ("appointment__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="agenda_item_note_exactly_one_target",
                    )
                ],
            },
        ),
    ]
