# Generated by Django 5.2.14 on 2026-06-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0008_agendaitemnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="modality",
            field=models.CharField(
                choices=[
                    ("office", "Consultorio u Oficina"),
                    ("phone", "Telefónica"),
                    ("video", "Video Llamada"),
                    ("offsite", "Fuera de la Instalación"),
                ],
                db_index=True,
                default="office",
                help_text="Modalidad: consultorio, telefónica, video o fuera de la instalación.",
                max_length=12,
            ),
        ),
    ]
