# Generated by Django 5.2.14 on 2026-06-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0009_appointment_modality"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reschedule_count",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Cuántas veces se ha reagendado esta cita."
            ),
        ),
    ]
