# Generated by Django 5.2.15 on 2026-06-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0010_appointment_reschedule_count"),
        ("finanzas", "0002_enable_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                help_text="Cotización aceptada que originó esta cita (opcional). Solo se puede vincular una Quote en estado ACCEPTED. Si la cotización se elimina, la FK queda en null (SET_NULL).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="finanzas.quote",
            ),
        ),
    ]
