# Generated by Django 5.2.15 on 2026-07-14 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0013_rls_with_check"),
        ("clinica", "0018_rls_membership_sucursales"),
        ("finanzas", "0006_serviceconcept_clinical_description"),
        ("pacientes", "0014_rls_with_check"),
        ("personal", "0009_backfill_sucursal_principal"),
        ("tenancy", "0005_seed_plans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agendablock",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal (sede) del evento (multi-sede — Fase 2). Determina el alcance de un bloqueo SIN doctor ni consultorio ('de toda la clínica' pasó a ser 'de una sucursal': un cierre en Centro ya NO bloquea Norte). Un bloqueo con doctor sigue aplicando en TODAS las sedes de ese médico; uno con consultorio, solo a ese cuarto. Se resuelve automáticamente si no se indica explícitamente.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agenda_blocks",
                to="clinica.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                help_text="Sucursal (sede) donde se agenda la cita (multi-sede — Fase 2). Se resuelve automáticamente en appointment_create si no se indica explícitamente (consultorio.sucursal → sede activa del request → sede predeterminada del tenant). Null = dato legado sin backfillar. La disponibilidad del MÉDICO sigue siendo GLOBAL entre sedes (ver _check_doctor_overlap); solo los bloqueos 'de toda la clínica' quedan acotados por sucursal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="clinica.sucursal",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["tenant", "sucursal", "starts_at"], name="appt_sucursal_range_idx"
            ),
        ),
    ]
