# Generated by Django 5.2.15 on 2026-07-21 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0015_backfill_appointment_agendablock_sucursal"),
        ("tenancy", "0005_seed_plans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantagendaconfig",
            name="agenda_end_hour",
            field=models.PositiveSmallIntegerField(
                default=18,
                help_text="Hora (1-24) a la que cierra la rejilla de la agenda. EXCLUSIVA: la última franja mostrada termina a esta hora. Ejemplo: 18 = cierra a las 18:00. Debe ser mayor que agenda_start_hour.",
            ),
        ),
        migrations.AddField(
            model_name="tenantagendaconfig",
            name="agenda_start_hour",
            field=models.PositiveSmallIntegerField(
                default=9,
                help_text="Hora (0-23) a la que abre la rejilla de la agenda. Ejemplo: 9 = 9:00 am.",
            ),
        ),
        migrations.AddField(
            model_name="tenantagendaconfig",
            name="slot_interval_minutes",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "5 minutos"),
                    (10, "10 minutos"),
                    (15, "15 minutos"),
                    (20, "20 minutos"),
                    (30, "30 minutos"),
                    (60, "60 minutos"),
                ],
                default=30,
                help_text="Cada cuántos minutos hay una línea en la rejilla de la agenda.",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantagendaconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("agenda_start_hour__gte", 0), ("agenda_start_hour__lte", 23)),
                name="agenda_config_start_hour_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantagendaconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("agenda_end_hour__gte", 1), ("agenda_end_hour__lte", 24)),
                name="agenda_config_end_hour_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantagendaconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("agenda_end_hour__gt", models.F("agenda_start_hour"))),
                name="agenda_config_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantagendaconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot_interval_minutes__in", [5, 10, 15, 20, 30, 60])),
                name="agenda_config_slot_interval_choices",
            ),
        ),
    ]
